# Learn more about Configuration as Code: https://docs.gatling.io/reference/execute/cloud/user/configuration-as-code
# This file is full deployment configuration file example.
# Please note all these configuration fields, or even this file, are optional.

gatling.enterprise.package {
  # Consistent deployment using an existing package ID
  # https://docs.gatling.io/reference/execute/cloud/user/configuration-as-code/#consistent-deployment-with-id
  id = "package_557rx6sfq7g8db5ywaabphkjkr"
  name = "ign-test-package"
  team = "Default" # or ID with team = "00000000-0000-0000-0000-000000000000"
  default {
    simulation {
      locations = [
        {
          name: "Europe - Paris",
          size: 1
        }
      ]
    }
  }
  simulations = [
    {
      # Consistent deployment using an existing simulation ID
      # https://docs.gatling.io/reference/execute/cloud/user/configuration-as-code/#consistent-deployment-with-id
      id = "test_obdhuwfht3yy5fq77xpcqfp11e"
      name = "IGN simulation"
      # Name of the simulation (i.e.: prefix of the simulation file src/*.gatling.js)
      simulation = "ignSimulation"
    }
  ]
}
